# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Survey2GisDemo
                                 A QGIS plugin
 Survey2Gis QGIS Frontend evaluation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-24
        copyright            : (C) 2024 by csgis gbr.
        email                : toni.schoenbuchner@csgis.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Survey2GisDemo class from file Survey2GisDemo.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .survey_2_gis_demo import Survey2GisDemo
    return Survey2GisDemo(iface)
